proper error message when makepkg is run in a fresh (ie. just created and still not commited) package

diff --git a/pkgtools/makepkg b/pkgtools/makepkg
--- a/pkgtools/makepkg
+++ b/pkgtools/makepkg
@@ -294,7 +294,9 @@ fi
 
 if [ -n "$gitpaths" ]; then
 	head=`git log --pretty=format:%H -n1 $gitpaths`
-	[[ $? -eq 0 ]] || error "cannot build pkgver variable"
+	{ [[ $? -eq 0 ]] && [[ -n "$head" ]]; } \
+		|| error "cannot build the pkgver variable (git commit needed?)"
+
 	pkgver=`git-describe $head | sed -re 's/^[^[:digit:]]*//' -e 's/-/_/g'`
 	dirty="`git diff-index --name-only --relative $head $gitpaths`"
 	for dir in $gitpaths; do
